services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuu_app
    ports:
      - "8080:80"
    volumes:
      - /home/ec2-user/kuu_laravel_project:/var/www/html
      - ./.env:/var/www/html/.env  # ホストの.envファイルをコンテナにマウント（Laravelの環境設定）
    environment:
      - APP_ENV=staging
    restart: always
    command: apache2-foreground
